### ISSUE TITLE
Installation Section

### ISSUE THREAD

**Issue by lfarah** [burhanuddin353/TFTColor#1]
Hey, your library is really interesting.

The only problem I found was the `README.md`, which lacks an `Installation Section`
I created this [iOS Open source Readme Template](https://github.com/awesome-labs/iOS-readme-template) so you can take a look on how to easily create an `Installation Section`
If you want, I can help you to organize the lib.

What are your thoughts? 😄

**Comment by burhanuddin353** [comment]
Updated!

Thanks for the reference, really **awesome** template. :]
